version: '3.7'

services:
  bot:
    build:
      context: .
    restart: unless-stopped
    env_file:
      - ./.env
    network_mode: 'host'
  
  mongo:
      image: mongo
      hostname: mongo
      restart: unless-stopped
      ports:
        -  '27017:27017'
      environment:
        MONGO_INITDB_ROOT_USERNAME: fyko
        MONGO_INITDB_ROOT_PASSWORD: doctordoctor
      volumes:
        - mongo_data:/data/db

volumes:
  mongo_data: