version: '2.4'

services:
  bot:
    build:
      context: .
    restart: unless-stopped
    env_file:
      - ./.env
    network_mode: 'host'
  
  mongo:
      image: mongo
      restart: unless-stopped
      environment:
        MONGO_INITDB_ROOT_USERNAME: fyko
        MONGO_INITDB_ROOT_PASSWORD: doctordoctor
      volumes:
        - mongo_data:/data/db

volumes:
  mongo_data: