version: '3.7'

services:
  bot:
    build:
      context: .
    restart: unless-stopped
    env_file:
      - ./.env
    network_mode: 'host'
    ports: 
      - '5501:5501'
    expose:
      - '5501'
  
  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: fyko
      POSTGRES_PASSWORD: doctordoctor
      POSTGRES_DB: giveaways
    ports:
      - 5432:5432

  redis:
    image: redis:6-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports: 
      - '6379:6379'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s

volumes:
  postgres_data:
  redis_data: